# Generated by Django 3.2 on 2022-08-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=11)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=11)),
            ],
        ),
    ]
